version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always

    container_name: npm
    ports:
      - '80:80'
      - '8081:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ""
      DB_MYSQL_PASSWORD: ""
      DB_MYSQL_NAME: ""
      TZ: "Asia/Tokyo"
    volumes:
      - /data/docker/volume/npm/data:/data
      - /data/docker/volume/npm/letsencrypt:/etc/letsencrypt
      - /data/docker/volume/npm/modules:/etc/nginx/modules
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
    volumes:
      - /data/docker/volume/npm/data/mysql:/var/lib/mysql

